/*
 * Bareflank Hypervisor
 *
 * Copyright (C) 2015 Assured Information Security, Inc.
 * Author: Bradley Hensel        <henselb@ainfosec.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 */

#ifndef HYP_MODULES_H
#define HYP_MODULES_H

#include "common.h"

#define HYPERVISOR_MODULE(mod)     \
extern unsigned char mod[];        \
extern unsigned int mod##_len;

#include "modules/modules.list"
#undef HYPERVISOR_MODULE

/**
 * Add hypervisor modules
 *
 * Adds modules from modules/modules.list to hypervisor
 * modules.list is generated by build script.
 *
 * @return uint64_t >= 0 if successful
 */
#define HYPERVISOR_MODULE(mod)                                      \
    ret = common_add_module((const char*)mod, (uint64_t)mod##_len); \
    if (ret < 0) {                                                  \
        Print(L"common_add_module returned %a\n", ec_to_str(ret));  \
        goto Abort;                                                 \
    }

uint64_t add_hypervisor_modules()
{
    int64_t ret;
    Print(L"Adding hypervisor modules\n");
#include "modules/modules.list"
    return ret;

Abort:
    return ret;
}
#undef HYPERVISOR_MODULE


#endif